_BASE_: "Base-Panoptic-FPN.yaml"
MODEL:
  WEIGHTS: "r2_101.pkl"
  RESNETS:
    DEPTH: 101
    SCALE: 4
    WIDTH_PER_GROUP: 26
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000

INPUT:
  FORMAT: "RGB"